### ISSUE TITLE
How to change the API level to 25 after using 23?

### ISSUE THREAD

**Issue by IAMtheIAM** [Lanchon/haystack#13]
I followed your instructions and used the API level 23. However I am using nougat and I realized the latest api is 25.

When I try to run the script again, it says `error already exists`

```
error: type 'com.android.server.pm.GeneratePackageInfoHook': direct method 'getGlobalEnable(android.content.pm.PackageInfo, android.content.Context, android.content.pm.PackageParser$Package, int, int):boolean': (GeneratePackageInfoHook.java:50): already exists
error: type 'com.android.server.pm.GeneratePackageInfoHook': direct method 'getPerAppEnable(android.content.pm.PackageInfo, android.content.Context, android.content.pm.PackageParser$Package, int, int):boolean': (GeneratePackageInfoHook.java:45): already exists
error: type 'com.android.server.pm.GeneratePackageInfoHook$FakeSignatureCore': (GeneratePackageInfoHook.java:0): already exists

```

How do I recompile the patch with an updated api level to 25? I tried pull-fileset again but it pulls the already patched files, I didn't make a backup of the original.

More importantly, will using API 25 instead of 23 on Nougat make any difference? Thanks

**Comment by Lanchon** [comment]
1) i've not validated that DexPatcher is compatible with Android 7.1. if 7.1 uses dex file version 037 as 7.0 does, then it is compatible. i need to update dexpatcher to the current smali release, including support for 7.1.

2) haystack is not a priori compatible with android 7.1. it needs to be validated at a minimum and updated. the fact that the patches applied in your case seem to imply that it is in fact compatible.

3) haystack was written against dexpatcher 1.1, which required explicit API level setting on the command line. dexpatcher 1.2 is able to autodetect, but haystack was never updated to support this.

4) "how do I recompile the patch...?" if you only want to apply patches (ie, use haystack) then you don't need to compile any patches.

5) "I tried pull-fileset again but it pulls the already patched files, I didn't make a backup of the original." lol, very bad thinking there :). pull the files from the flashable zip file of your rom (you'll need custom tools to do this). otherwise make a TWRP backup of you rom (system only), flash the unpatched exact same version of your rom again, pull fileset, restore backup.

6) "will using API 25 instead of 23 on Nougat make any difference?" if api 25 uses dex version == 037, then no difference whatsoever: you don't need to redo your work. but if api 25 uses dex version > 037, then dexpatcher doesn't support api 25: you need to redo your work but you can't!!!

**Comment by Lanchon** [comment]
i've updated DexPatcher to support Android 7.1, then updated haystack for same.

**Comment by IAMtheIAM** [comment]
Great, thanks for updating this. Does that mean I should use API 25 still? Should I repatch my phone now that you made this update?

**Comment by Lanchon** [comment]
if it works fine, i wouldn't touch it :)
