### ISSUE TITLE
Various Google Apps stop working with microG

### ISSUE THREAD

**Issue by Antonbeard** [Lanchon/haystack#41]
Google seemingly has updated their signature checking code. On Android 9 and above, the latest code uses PackageInfo.signingInfo (via GET_SINGNING_CERTIFICATES flags) instead of PackageInfo.signatures (via GET_SIGNATURES flag). This will likely roll out to non-Google apps in the future as well.

This means that all signature spoofing patches need to be updated to address the change of API usage by - in addition to the PackageInfo.signatures also spoofing the PackageInfo.signingInfo.

**Comment by Antonbeard** [comment]
There is a discussion with a solution https://github.com/microg/GmsCore/issues/2680

**Comment by Lanchon** [comment]
thanks, both of you. i've long ago stopped maintaining this. lineageos has long been including the necessary patches (after years of opposing them), so haystack is no longer needed. and regarding non-free OSes, i really don't care about them. thanks again.

**Comment by IsHacker003** [comment]
> thanks, both of you. i've long ago stopped maintaining this. lineageos has long been including the necessary patches (after years of opposing them), so haystack is no longer needed. and regarding non-free OSes, i really don't care about them. thanks again.

I don't have lineageOS, and already patched my Android 9 stock ROM. It works, and MicroG 0.3.5 and earlier detect signature spoofing support (Checkboxes aren't checked in 0.3.6) and so does your signature spoofing checker app. But unfortunately, no GApps work because of the issue of outdated APIs (as @Antonbeard said). Can you at least tell me what I should change to implement the new APIs, and how to build/compile the patch from source? It would be very helpful.
