### ISSUE TITLE
Unable to access jarfile when patching fileset

### ISSUE THREAD

**Issue by maciozo** [Lanchon/haystack#6]
```
Maciek@SkyNet2 /cygdrive/c/Users/Maciek/Desktop/haystack-master
$ ./patch-fileset patches/sigspoof-hook-4.1-6.0/ 25 d855/
>>> target directory: d855__sigspoof-hook-4.1-6.0
>>> apply patch: services.jar
>>> dexpatcher --api-level 25 --verbose --output d855__sigspoof-hook-4.1-6.0/tmp/services.jar/patched-dex --multi-dex d855/services.jar patches/sigspoof-hook-4.1-6.0/services.jar.dex
Error: Unable to access jarfile /cygdrive/c/Users/Maciek/Desktop/haystack-master/./dexpatcher/dexpatcher-1.2.0-beta2.1.jar
```

Running on Windows 8.1 with Cygwin. Tried with jdk 1.8.0_121 x86_64 and i586.

**Comment by Lanchon** [comment]
the dexpatcher executable jar file is not found, for whatever reason. i'm afraid you'll have to handle this yourself, i don't support proprietary stuff like windows. i couldn't repro if i wanted either.

you may consider "upgrading" to windows 10 (it may still be done for free) and running the WSL:
https://blogs.msdn.microsoft.com/wsl/2016/04/22/windows-subsystem-for-linux-overview/
but keep in mind that on win 10 MS can push ads to your desktop, lol. but sooner or later you'll have to migrate.

having native ubuntu/linux ELF support instead of cygwin is a whole different ballgame.

**Comment by maciozo** [comment]
Well, I managed to fix it by setting all the paths to Windows paths but with forward slashes.
